import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./ui/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={`${inter.className} flex min-h-screen flex-col`}>
               <div className='flex flex-grow flex-col justify-center'>
                 {children}
               </div>
               <Footer />
             </body>
    </html>
  );
}
